### ISSUE TITLE
A model matrix for estimating the effect of a covariate on treatment vs. control fold change between two groups

### ISSUE THREAD

**Issue by ndrubins** [eturro/mmseq#23]
Hi @eturro,

I'm wondering what would be the model design matrix and interpretation for estimating tissue effect (2 different tissues) on the treatment vs. control data from 2 groups - assuming I have 3 samples from each tissue,group, and treatment (altogether 24)

**Comment by eturro** [comment]
Do you want to test for an interaction between tissue and treatment (i.e. the effect of tissue is different for each treatment group) or do you want to simply assess whether there is a global tissue effect, after accounting for group and treatment?

**Comment by ndrubins** [comment]
Thanks a a lot for the reponse.

I guess the first option is what I need but I think it would be a tissue by
group by treatment interaction, right?

**Comment by eturro** [comment]
Hmm, that would mean assessing whether the effect of tissue differs between each of the four combinations of group and treatment. That would require several coefficients.

Would it be sensible to at least start with just assessing whether there is a difference in tissue effect between treatment groups, after _adjusting_ for group effect?

**Comment by ndrubins** [comment]
Let me give you a bit more information so you can understand the context
better. The two groups are two different species and one has a much better
assembled and annotated genome. Both species were treated with a harsh
stress agent and the controls are treatment with the vehicle alone. The
species with the less well assembled genome has on average higher
expression levels since reads have less locations to ambiguously map to.
The questions are straight forward: what are the different responses to the
treatment between the two species and how is that affected by tissue.
Because of the read mapping issue it only nakes sense to contrast treatment
vs vehicle between the species. The simple minded way to get the tissue
effect is simply analyze each tissue separately and then just look what's
inside and outside the intersection but that's cutoff dependent.

If I understand your idea correctly it won't answer the question that I'm
after- how does the species response/effect vary by tissue. Did I
understand you correctly ?

Thanks a lot for your help

**Comment by eturro** [comment]
Thanks for clarifying

Based on what you've said about the reference transcriptomes, I would suggest always including a species effect; that would take care of any differences due to the differing concentration of reads that you mentioned.

You could compare four models

0) baseline model including one regression coefficient, representing:
- log FC between the two species

1)
- log FC between the two species
- log FC between treatments

2)
- log FC between the two species
- log FC between tissues
- log FC between treatments

3)
- log FC between the two species
- log FC between tissues
- log FC between treatments in species 1
- log FC between treatments in species 2


(I'm ignoring the intercept)

So that's three pairwise comparisons you should run (three runs of mmdiff).

You would then read in the results in the order above using the polyclass() R function in mmseq.R , specifying the vector of prior probabilities of the four different models in the corresponding order.

I've pasted in the contents of the three matrices files I think you should use (assuming only two reps instead of three, for simplicity).

hope this helps
Ernest

---- Comparison 1:
# Use this order
# species 1, tissue 1, vehicle
# species 1, tissue 1, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 1, treatment
# species 1, tissue 1, treatment
# species 1, tissue 2, treatment
# species 1, tissue 2, treatment
# species 2, tissue 1, vehicle
# species 2, tissue 1, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 1, treatment
# species 2, tissue 1, treatment
# species 2, tissue 2, treatment
# species 2, tissue 2, treatment
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
0 0
0 1
0 1
0 1
0 1
1 0
1 0
1 0
1 0
1 1
1 1
1 1
1 1
# P0(collapsed); no. of rows = no. of classes for model 0
0.5
-.5
# P1(collapsed); no. of rows = no. of classes for model 1
0.5 0.5
0.5 -.5
-.5 0.5
-.5 -.5


--- Comparison 2:
# Use this order
# species 1, tissue 1, vehicle
# species 1, tissue 1, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 1, treatment
# species 1, tissue 1, treatment
# species 1, tissue 2, treatment
# species 1, tissue 2, treatment
# species 2, tissue 1, vehicle
# species 2, tissue 1, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 1, treatment
# species 2, tissue 1, treatment
# species 2, tissue 2, treatment
# species 2, tissue 2, treatment
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 1
0 1
0 2
0 2
0 3
0 3
1 4
1 4
1 5
1 5
1 6
1 6
1 7
1 7
# P0(collapsed); no. of rows = no. of classes for model 0
0.5
-.5
# P1(collapsed); no. of rows = no. of classes for model 1
0.5 0.5 0.5
0.5 -.5 0.5
0.5 0.5 -.5
0.5 -.5 -.5
-.5 0.5 0.5
-.5 -.5 0.5
-.5 0.5 -.5
-.5 -.5 -.5


--- Comparison 3:
# Use this order
# species 1, tissue 1, vehicle
# species 1, tissue 1, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 2, vehicle
# species 1, tissue 1, treatment
# species 1, tissue 1, treatment
# species 1, tissue 2, treatment
# species 1, tissue 2, treatment
# species 2, tissue 1, vehicle
# species 2, tissue 1, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 2, vehicle
# species 2, tissue 1, treatment
# species 2, tissue 1, treatment
# species 2, tissue 2, treatment
# species 2, tissue 2, treatment
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 1
0 1
0 2
0 2
0 3
0 3
1 4
1 4
1 5
1 5
1 6
1 6
1 7
1 7
# P0(collapsed); no. of rows = no. of classes for model 0
0.5
-.5
# P1(collapsed); no. of rows = no. of classes for model 1
0.5 0.5 0.5 0
0.5 -.5 0.5 0
0.5 0.5 -.5 0
0.5 -.5 -.5 0
-.5 0.5 0   0.5
-.5 -.5 0   0.5
-.5 0.5 0   -.5
-.5 -.5 0   -.5

**Comment by ndrubins** [comment]
Thanks a lot!!!
