### ISSUE TITLE
A model matrix for estimating the effect of a numeric variable on expression levels

### ISSUE THREAD

**Issue by ndrubins** [eturro/mmseq#25]
Hi @eturro ,

A couple of more questions about setting up model matrices:

1. I have a time course data (3 samples obtained at 1h, 5h, 10h, and 24h) and I'd like to estimate the effect of time on expression.

What would be the appropriate model matrix for this design?
Is it simply:

```
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 1
0 1
0 1
0 5
0 5
0 5
0 10
0 10
0 10
0 24
0 24
0 24
# P0(collapsed); no. of rows = no. of classes for model 0
1
# P1(collapsed); no. of rows = no. of classes for model 1
.5
-.5

```
2. Same as in question 1 but in this case I have treatment and control samples (3 and 3) for each of the time points and I want to estimate the interaction between treatment and time  - i.e., is the slope of the treatment different from the slope of the control.

What would be the appropriate model matrix for this design?
Would it be comparing a model with no treatment and control with a model with treatment and control?

So the no treatment and control model matrix: would be:

```
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 1
0 1
0 1
0 1
0 1
0 1
0 5
0 5
0 5
0 5
0 5
0 5
0 10
0 10
0 10
0 10
0 10
0 10
0 24
0 24
0 24
0 24
0 24
0 24
# P0(collapsed); no. of rows = no. of classes for model 0
1
# P1(collapsed); no. of rows = no. of classes for model 1
.5
-.5

```
And the treatment and control model matrix will be:

```
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 1
0 1
0 1
0 5
0 5
0 5
0 10
0 10
0 10
0 24
0 24
0 24
1 1
1 1
1 1
1 5
1 5
1 5
1 10
1 10
1 10
1 24
1 24
1 24
# P0(collapsed); no. of rows = no. of classes for model 0
0.5
-.5
# P1(collapsed); no. of rows = no. of classes for model 1
0.5 0.5
0.5 -.5
-.5 0.5
-.5 -.5

```
Thanks a lot

**Comment by eturro** [comment]
>  I'd like to estimate the effect of time on expression.

I'm afraid you need to be more specific. mmdiff compares models so you need to first specify the models as simple linear regression models, and then I can help you with encoding them in the matrices file.

In any case I can tell you already that your "C" section is wrong, as each column must contain indices, starting at zero and going up in increments of one. These indices effectively group observations.

Furthermore, the P1 section should contain a number of rows equal to the number of different indices for the alternate model.

In your example, you have four indices (which should be labelled 0, 1, 2, 3) and only two rows under P1, so there is a mismatch.

Anyway, as I say you need to specify the linear regression models first; do you want a linear change over the time points? or separate coefficient for each consecutive time transition? Would your baseline model be one with a global mean? As you know, you can specify multiple alternate models and then compare them with each other.

Perhaps the simplest thing would be to assume that there is a linear change from 1h to 5h to 10h to 24h, if that's realistic. So that model would contain a single regression coefficient.

Let me know. We can then deal with the more complex case with treatment groups.

**Comment by ndrubins** [comment]
Thanks a lot for the quick response.

In my data `time` is a numeric variable and in the first case I want to estimate the linear change over the time points. i.e. the slope of the line fitted to the four time points - so the model with the single regression coefficient is what I'm looking for.

In `R` `lm` syntax, if the `data.frame` with these data are:
`df <- data.frame(y = rnorm(12), time = c(rep(1,3),rep(5,3),rep(10,3),rep(24,3)))
`
The model would therefore be:
`lm(y ~ time, data = df)
`

In the second case, in  `R` `lm` syntax, the `data.frame` would be:
`df <- data.frame(y = rnorm(24), time = rep(c(rep(1,3),rep(5,3),rep(10,3),rep(24,3)),2), group = c(rep("control",12),rep("treatment",12)))
df$group <- factor(df$group, levels = c("control","treatment"))
`

And the model would be:
`lm(y ~ group*time, data = df)`

Where the coefficient of interest is:
`grouptreatment:time
`

That said, the expression of many genes does not follow a straight line along time and in that case the model above would poorly fit and the interpretation would not be meaningful.
For the second case specifically a complementary analysis I was thinking of is to simply fitt the model that tests if [log fold change between group A and group B is different (as opposed to equal) to the log fold change between group C and group D](https://raw.githubusercontent.com/eturro/mmseq/master/doc/dod2.mat)
to each time interval defined by two consecutive time points (i.e., a total of 3 intervals), and then making some sense of that, e.g., noting if there's a sign change in `eta1_0` across the three models fitted to the three time intervals.
Clearly, the same can be done for the first case as well.

Is there any explicit model that can be define through MMDIFF that would be more appropriate than that?

Thanks a lot

**Comment by ndrubins** [comment]
Hi @eturro,

Hope I'm not nudging too much - just curious if you got a chance to read my clarification on the model setup.

Thanks a lot

**Comment by eturro** [comment]
Hi ndrubins, sorry for the delay.

Before I get on to the second case, I need to ask you to clarify something about the first case.

Your R example does not show "a linear change over the time points" because your time points are not equally spaced and they are coded as a numeric variable, not as a factor.

This would be a linear change over time, not over the time points:

time point: expected value
1: 0
5: 2.5
10: 5
24: 12

this would be a linear change over the time points:

time point: expected value
1: 0
5: 2.5
10: 5
24: 7.5

Which of the two are you after

thanks

**Comment by ndrubins** [comment]
Hi @eturro,

Thanks for the response.

I guess I misused the term **time points** and I really meant **linear change over time**, hence time is a numeric variable. Thus, although my time points are not equally spaced the estimated time effect in my `R` `lm`, i.e., the slope of the fitted line, would be the change that 1 unit of time has on expression.

Therefore the first option you provide is the correct one.

Thanks a lot.

**Comment by eturro** [comment]
OK, got it, thanks. (by the way my example wasn't quite right.. I was treating your time point 1 as time point 0).

Note that I assume there is no pairing across time points as you would have in longitudinal data

So, if you wish to check whether the slope is non-zeo, assuming you have three biological samples per time point, you could use the following:

# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
0 1
0 1
0 1
0 2
0 2
0 2
0 3
0 3
0 3
# P0(collapsed); no. of rows = no. of classes for model 0
1
# P1(collapsed); no. of rows = no. of classes for model 1
0
0.1739130
0.3913043
1


I obtained the predictor as follows - 

> x=c(1,5,10,24);(x-min(x))/max(x-min(x))
[1] 0.0000000 0.1739130 0.3913043 1.0000000

so the interpretation of eta is the expected log fold change between time points 1 and 24.


In the second case, I assume you want to allow for both a different mean between treatment and control and also a different slope. So I suggest comparing a baseline model in which there is a different mean and the same slope to one in which there is a different mean and a different slope.


# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
0 1
0 1
0 1
0 2
0 2
0 2
0 3
0 3
0 3
1 4
1 4
1 4
1 5
1 5
1 5
1 6
1 6
1 6
1 7
1 7
1 7

# P0(collapsed); no. of rows = no. of classes for model 0
-.5 0
-.5 0.1739130
-.5 0.3913043
-.5 1

# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0 0
-.5 0.1739130 0
-.5 0.3913043 0
-.5 1 0
.5 0 0
.5 0 0.1739130
.5 0 0.3913043
.5 0 1


> In the second case, in R lm syntax, the data.frame would be:
> df <- data.frame(y = rnorm(24), time = rep(c(rep(1,3),rep(5,3),rep(10,3),rep(24,3)),2), group = c(rep("control",12),rep("treatment",12)))

> df$group <- factor(df$group, levels = c("control","treatment"))
> 
> And the model would be:
> lm(y ~ group*time, data = df)
> 
> Where the coefficient of interest is:
> grouptreatment:time
> 
> That said, the expression of many genes does not follow a straight line along time and in that case the model above would poorly fit and the interpretation would not be meaningful.
> For the second case specifically a complementary analysis I was thinking of is to simply fitt the model that tests if log fold change between group A and group B is different (as opposed to equal) to the log fold change between group C and group D
> to each time interval defined by two consecutive time points (i.e., a total of 3 intervals), and then making some sense of that, e.g., noting if there's a sign change in eta1_0 across the three models fitted to the three time intervals.
> Clearly, the same can be done for the first case as well.
> 
> Is there any explicit model that can be define through MMDIFF that would be more appropriate than that?
> 
> Thanks a lot

**Comment by ndrubins** [comment]
Thanks a lot.

Just a couple of clarification questions:

1. I'm not sure I understand the choice of obtaining the predictor. Does the expected value have to be the log fold change between time points 1 and 24? Do the minimum and maximum values of the predictor have to be 0 and 1?

I'm used to having the slope being the estimated effect size (i.e., the expected fold-change) per one unit of time (in this case 1 hour).  I guess that I can divide the eta estimated by this parametrization by 24 to get that but is there a direct way of obtaining that with a different predictor?

2. In the case of question 2, If I were to assume equal means for treatment and control, would the parametrization simply be:

```
# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
0 1
0 1
0 1
0 2
0 2
0 2
0 3
0 3
0 3
0 4
0 4
0 4
0 5
0 5
0 5
0 6
0 6
0 6
0 7
0 7
0 7

# P0(collapsed); no. of rows = no. of classes for model 0
-.5 0
-.5 0.1739130
-.5 0.3913043
-.5 1

# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0 0
-.5 0.1739130 0
-.5 0.3913043 0
-.5 1 0
.5 0 0
.5 0 0.1739130
.5 0 0.3913043
.5 0 1

```

Thanks a lot

**Comment by ndrubins** [comment]
Sorry for nagging, but I have one more question. In the second case, is that parameterization for a single run that contrasts the two models (different means same slopes vs. different means and different slopes)? I see that the `M` matrix has only half of the samples. I tried running this, but initially filled `M` with 24 rows (same as in `C`) but that exited with this error:
`Error: more distinct rows of P than classes for model 0 (2 > 1).
`
Is `P0` missing 4 additional rows?

**Comment by eturro** [comment]
> 	• I'm not sure I understand the choice of obtaining the predictor. Does the expected value have to be the log fold change between time points 1 and 24? Do the minimum and maximum values of the predictor have to be 0 and 1?
> I'm used to having the slope being the estimated effect size (i.e., the expected fold-change) per one unit of time (in this case 1 hour). I guess that I can divide the eta estimated by this parametrization by 24 to get that but is there a direct way of obtaining that with a different predictor?

The predictor can be anything you like. However, the variance of the predictor should be consistent with the variance of its prior distribution. The default prior on eta will work will with the scaling I have given you. E.g., for standard differential expression we normally use (-0.5, ..., 0.5, ...)^T, so that the estimated eta can be interpreted as the log fold change.

> 	• In the case of question 2, If I were to assume equal means for treatment and control, would the parametrization simply be:

I would not recommend this unless you have a good reason for making that assumption. By the way, I'm sorry, I just noticed I made a mistake in my previous email. It should be:

# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
1 1
1 1
1 1
2 2
2 2
2 2
3 3
3 3
3 3
4 4
4 4
4 4
5 5
5 5
5 5
6 6
6 6
6 6
7 7
7 7
7 7

# P0(collapsed); no. of rows = no. of classes for model 0
-.5 0
-.5 0.1739130
-.5 0.3913043
-.5 1
.5 0
.5 0.1739130
.5 0.3913043
.5 1

# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0 0
-.5 0.1739130 0
-.5 0.3913043 0
-.5 1 0
.5 0 0
.5 0 0.1739130
.5 0 0.3913043
.5 0 1



If you wanted to assume equal means between treatment and control (I do not recommend this), then you would simply remove the first coefficient from each model:


# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
0
0

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
1 1
1 1
1 1
2 2
2 2
2 2
3 3
3 3
3 3
0 4
0 4
0 4
1 5
1 5
1 5
2 6
2 6
2 6
3 7
3 7
3 7

# P0(collapsed); no. of rows = no. of classes for model 0
0
0.1739130
0.3913043
1

# P1(collapsed); no. of rows = no. of classes for model 1
0 0
0.1739130 0
0.3913043 0
1 0
0 0
0 0.1739130
0 0.3913043
0 1

**Comment by eturro** [comment]
You're quite right apologies! Just pad out with '0' up to the total number of samples.

**Comment by ndrubins** [comment]
Thanks a lot
